directory_name: ariit_temp_pkg
pkg_names: ['temp_pkg1' 'temp_pkg2' 'temp_pkg3']
node_names: ['temp_pkg1_node' 'temp_pkg2_node' 'temp_pkg3_node']
dependencies: 
	- ['depen1' 'depen2' 'depen3']
	- ['depen1' 'depen2']
	- ['depen1']

